### ISSUE TITLE
boot error

### ISSUE THREAD

**Issue by brbdaniele** [razman786/i8kgui#28]
if I start from i8kgui applications it will not boot.
if boot from terminal I get the following error
"Found: Intel CPU
Found: Sysfs AC power supply
Found: Sysfs scaling governor
Found: Sysfs RAPL TDP
Found: Sysfs SMT status
Found: Sysfs CPU siblings
Found Intel sensors:
Sensor: shwtemp(label='Package id 0', current=71.0, high=86.0, critical=100.0)
Sensor: shwtemp(label='Core 0', current=70.0, high=86.0, critical=100.0)
Sensor: shwtemp(label='Core 1', current=72.0, high=86.0, critical=100.0)
Sensor: shwtemp(label='Core 2', current=68.0, high=86.0, critical=100.0)
Sensor: shwtemp(label='Core 3', current=65.0, high=86.0, critical=100.0)
Found: 4 Sysfs Intel coretemps
Found: Sysfs CPU Turbo
Found: Sysfs CPU min perf
Found: Sysfs CPU max perf
Found: Sysfs CPU min scaling
Found: Sysfs CPU max scaling
Found: dell_smm_hwmon fan1
Found: dell_smm_hwmon fan1_target
Error: dell_smm_hwmon fan2 not found
Found: dell_smm_hwmon CPU temp
Found: i8kmon.service is active
Found: dell-bios-fan-control.service is active
Found: i8kctl /usr/bin/i8kctl
Found: i8kmon config file /etc/i8kmon.conf
Error: (SM)BIOS Thermal Control not found
Info: switching thermal mode to enable i8k
Found: CPU SMT active? True
Found: 4 CPU Cores
Found: 8 Logical CPU Cores
Found: 8 CPU siblings in list
Found: CPU siblings: {0: 4, 1: 5, 2: 6, 3: 7, 4: 0, 5: 1, 6: 2, 7: 3}
Found: CPU temp sensors [0, 1, 2, 3, 0, 1, 2, 3]
Warn: Sysfs IOError [Errno 2] File o directory non esistente: '/some/where/0'
Warn: Sysfs IOError [Errno 2] File o directory non esistente: '/some/where/0'
Traceback (most recent call last):
  File "/home/danida/.local/bin/i8kgui", line 2087, in open_sysfs_file
    f = open(f_name, mode)
FileNotFoundError: [Errno 2] File o directory non esistente: '/some/where/0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/danida/.local/bin/i8kgui", line 2009, in monitor
    self.read_proc()
  File "/home/danida/.local/bin/i8kgui", line 1913, in read_proc
    self.read_i8kmon_info()
  File "/home/danida/.local/bin/i8kgui", line 1778, in read_i8kmon_info
    self.update_i8k_thermal()
  File "/home/danida/.local/bin/i8kgui", line 1976, in update_i8k_thermal
    left_speed = f"{value[value.index(str(self.left_fan_mode))]}".rjust(
ValueError: '3321' is not in list

"

**Comment by razman786** [comment]
Hi @brbdaniele 
Can you paste your `i8kmon.conf` file please? I need to see this section: https://github.com/razman786/i8kgui/blob/f73f2ae53b33b516f12f612ee125901e45b8455a/i8kmon_sample_conf/i8kmon.conf#L29

**Comment by razman786** [comment]
@brbdaniele - I'm closing this issue due to inactivity. Please re-open the issue if you still need help.
